import type { PortfolioHolding, ScenarioEvent, SeverityLevel, TimeHorizon } from "./types";

export const TOTAL_PORTFOLIO_MARKET_VALUE = 123.2;
export const MAP_CENTER: [number, number] = [37.5, -95.5];
export const INITIAL_ZOOM = 4;
export const MARKER_PIXELS = { large: 54, medium: 46, small: 38 } as const;

export const SCENARIO_EVENTS: ScenarioEvent[] = [
  {
    id: "hurricane",
    icon: "🌀",
    label: "Gulf Coast Hurricane",
    summaryLabel: "Gulf Coast",
    epicenter: [27.5, -90.5],
    footprintType: "radius",
    primaryDrivers: ["Gulf Coast asset concentration", "Offshore energy infrastructure"],
  },
  {
    id: "wildfire",
    icon: "🔥",
    label: "California Wildfire",
    summaryLabel: "California",
    epicenter: [38.5, -121.0],
    footprintType: "radius",
    primaryDrivers: ["California infrastructure exposure", "Utility and communications assets"],
  },
  {
    id: "flood",
    icon: "🌊",
    label: "Mississippi River Flood",
    summaryLabel: "Mississippi River",
    epicenter: [32.0, -91.0],
    footprintType: "radius",
    primaryDrivers: ["River basin logistics disruption", "Gulf processing corridor"],
  },
  {
    id: "drought",
    icon: "☀️",
    label: "Texas Drought",
    summaryLabel: "Texas",
    epicenter: [31.5, -99.0],
    footprintType: "radius",
    primaryDrivers: ["Water stress on industrial assets", "Power and cooling constraints"],
  },
  {
    id: "carbon",
    icon: "⚡",
    label: "Carbon Tax Shock",
    summaryLabel: "Systemic Transition Shock",
    footprintType: "systemic",
    primaryDrivers: ["Carbon-policy-sensitive states", "Energy transition multiple compression"],
  },
];

export const SEVERITY_LABELS: Record<SeverityLevel, string> = {
  1: "Cat 1",
  2: "Cat 2",
  3: "Cat 3",
  4: "Cat 4",
  5: "Cat 5",
};

export const TIME_HORIZON_LABELS: Record<TimeHorizon, string> = {
  "1w": "1 Week",
  "1m": "1 Month",
  "1q": "1 Quarter",
  "1y": "1 Year",
};

export const SEVERITY_RADII: Record<SeverityLevel, number> = {
  1: 150000,
  2: 250000,
  3: 350000,
  4: 450000,
  5: 600000,
};

export const MOCK_PORTFOLIO: PortfolioHolding[] = [
  {
    id: "cvx",
    ticker: "CVX",
    companyName: "Chevron",
    positionType: "LONG",
    markerSize: "large",
    coordinates: [29.7604, -95.3698],
    sector: "Integrated Energy",
    positionMarketValue: 18.4,
    portfolioWeight: 14.9,
    annualRevenue: 198000,
    ebitdaMargin: 0.19,
    debt: 27800,
    interestExpense: 1120,
    sharesOrExposureUnits: 112000,
    baselineValuationMultiple: 6.9,
    dailyRevenue: 542,
    repairCostSensitivity: 1.35,
    recoverySpeed: 0.72,
    hedgeRelevanceScore: 0.88,
    geographicExposure: { hurricane: 0.84, wildfire: 0.08, flood: 0.58, drought: 0.41, carbon: 0.74 },
    facilitiesInImpactZonePct: { hurricane: 0.68, wildfire: 0.04, flood: 0.44, drought: 0.26, carbon: 0.71 },
    climateSensitivity: { physicalDamage: 1.4, revenue: 1.28, cost: 1.32, credit: 1.08, valuation: 1.04 },
    thematicDrivers: ["Gulf Coast asset concentration", "Offshore energy infrastructure", "Refining corridor exposure"],
  },
  {
    id: "xom",
    ticker: "XOM",
    companyName: "ExxonMobil",
    positionType: "SHORT",
    markerSize: "large",
    coordinates: [32.7767, -96.797],
    sector: "Integrated Energy",
    positionMarketValue: 16.1,
    portfolioWeight: 13.1,
    annualRevenue: 221000,
    ebitdaMargin: 0.18,
    debt: 41200,
    interestExpense: 1380,
    sharesOrExposureUnits: 93000,
    baselineValuationMultiple: 7.3,
    dailyRevenue: 605,
    repairCostSensitivity: 1.24,
    recoverySpeed: 0.68,
    hedgeRelevanceScore: 0.95,
    geographicExposure: { hurricane: 0.69, wildfire: 0.05, flood: 0.31, drought: 0.46, carbon: 0.82 },
    facilitiesInImpactZonePct: { hurricane: 0.54, wildfire: 0.02, flood: 0.21, drought: 0.33, carbon: 0.79 },
    climateSensitivity: { physicalDamage: 1.22, revenue: 1.16, cost: 1.21, credit: 1.12, valuation: 1.08 },
    thematicDrivers: ["Gulf Coast asset concentration", "Carbon-policy-sensitive states", "Hydrocarbon multiple compression"],
  },
  {
    id: "hal",
    ticker: "HAL",
    companyName: "Halliburton",
    positionType: "LONG",
    markerSize: "medium",
    coordinates: [29.8164, -95.3218],
    sector: "Oilfield Services",
    positionMarketValue: 12.7,
    portfolioWeight: 10.3,
    annualRevenue: 23800,
    ebitdaMargin: 0.17,
    debt: 7900,
    interestExpense: 420,
    sharesOrExposureUnits: 146000,
    baselineValuationMultiple: 7.8,
    dailyRevenue: 65,
    repairCostSensitivity: 1.48,
    recoverySpeed: 0.62,
    hedgeRelevanceScore: 0.64,
    geographicExposure: { hurricane: 0.81, wildfire: 0.06, flood: 0.42, drought: 0.34, carbon: 0.49 },
    facilitiesInImpactZonePct: { hurricane: 0.61, wildfire: 0.03, flood: 0.29, drought: 0.22, carbon: 0.35 },
    climateSensitivity: { physicalDamage: 1.36, revenue: 1.34, cost: 1.37, credit: 1.18, valuation: 1.06 },
    thematicDrivers: ["Gulf Coast asset concentration", "Oilfield service dependency", "Refining corridor exposure"],
  },
  {
    id: "spg",
    ticker: "SPG",
    companyName: "Simon Property",
    positionType: "LONG",
    markerSize: "medium",
    coordinates: [25.7617, -80.1918],
    sector: "Retail REIT",
    positionMarketValue: 14.8,
    portfolioWeight: 12.0,
    annualRevenue: 5800,
    ebitdaMargin: 0.52,
    debt: 24800,
    interestExpense: 910,
    sharesOrExposureUnits: 61000,
    baselineValuationMultiple: 13.2,
    dailyRevenue: 15.9,
    repairCostSensitivity: 1.12,
    recoverySpeed: 0.58,
    hedgeRelevanceScore: 0.32,
    geographicExposure: { hurricane: 0.62, wildfire: 0.09, flood: 0.78, drought: 0.08, carbon: 0.24 },
    facilitiesInImpactZonePct: { hurricane: 0.46, wildfire: 0.06, flood: 0.64, drought: 0.03, carbon: 0.16 },
    climateSensitivity: { physicalDamage: 1.08, revenue: 1.22, cost: 1.12, credit: 1.14, valuation: 1.18 },
    thematicDrivers: ["Coastal real estate exposure", "FEMA flood corridor", "Tourism-dependent cash flows"],
  },
  {
    id: "nee",
    ticker: "NEE",
    companyName: "NextEra Energy",
    positionType: "LONG",
    markerSize: "medium",
    coordinates: [26.7153, -80.0534],
    sector: "Utility",
    positionMarketValue: 13.9,
    portfolioWeight: 11.3,
    annualRevenue: 28700,
    ebitdaMargin: 0.34,
    debt: 76400,
    interestExpense: 2140,
    sharesOrExposureUnits: 78000,
    baselineValuationMultiple: 11.6,
    dailyRevenue: 78.6,
    repairCostSensitivity: 1.21,
    recoverySpeed: 0.71,
    hedgeRelevanceScore: 0.43,
    geographicExposure: { hurricane: 0.57, wildfire: 0.04, flood: 0.71, drought: 0.18, carbon: 0.36 },
    facilitiesInImpactZonePct: { hurricane: 0.49, wildfire: 0.02, flood: 0.59, drought: 0.14, carbon: 0.22 },
    climateSensitivity: { physicalDamage: 1.18, revenue: 0.86, cost: 1.24, credit: 1.09, valuation: 1.02 },
    thematicDrivers: ["Utility infrastructure exposure", "Coastal transmission network", "Regulated recovery lag"],
  },
  {
    id: "amt",
    ticker: "AMT",
    companyName: "American Tower",
    positionType: "LONG",
    markerSize: "small",
    coordinates: [37.3382, -121.8863],
    sector: "Communications Infrastructure",
    positionMarketValue: 11.4,
    portfolioWeight: 9.3,
    annualRevenue: 11000,
    ebitdaMargin: 0.62,
    debt: 40300,
    interestExpense: 1280,
    sharesOrExposureUnits: 54000,
    baselineValuationMultiple: 18.5,
    dailyRevenue: 30.1,
    repairCostSensitivity: 1.09,
    recoverySpeed: 0.76,
    hedgeRelevanceScore: 0.18,
    geographicExposure: { hurricane: 0.06, wildfire: 0.74, flood: 0.05, drought: 0.22, carbon: 0.68 },
    facilitiesInImpactZonePct: { hurricane: 0.01, wildfire: 0.58, flood: 0.01, drought: 0.11, carbon: 0.54 },
    climateSensitivity: { physicalDamage: 1.17, revenue: 0.74, cost: 1.03, credit: 0.94, valuation: 1.1 },
    thematicDrivers: ["California infrastructure exposure", "Tower backup-power costs", "Digital infrastructure multiple risk"],
  },
  {
    id: "lyb",
    ticker: "LYB",
    companyName: "LyondellBasell",
    positionType: "LONG",
    markerSize: "small",
    coordinates: [29.7604, -95.8],
    sector: "Chemicals",
    positionMarketValue: 17.3,
    portfolioWeight: 14.0,
    annualRevenue: 41200,
    ebitdaMargin: 0.14,
    debt: 10300,
    interestExpense: 390,
    sharesOrExposureUnits: 118000,
    baselineValuationMultiple: 6.4,
    dailyRevenue: 112.9,
    repairCostSensitivity: 1.42,
    recoverySpeed: 0.57,
    hedgeRelevanceScore: 0.51,
    geographicExposure: { hurricane: 0.64, wildfire: 0.05, flood: 0.51, drought: 0.43, carbon: 0.69 },
    facilitiesInImpactZonePct: { hurricane: 0.55, wildfire: 0.02, flood: 0.38, drought: 0.29, carbon: 0.61 },
    climateSensitivity: { physicalDamage: 1.39, revenue: 1.19, cost: 1.33, credit: 1.1, valuation: 1.03 },
    thematicDrivers: ["Gulf Coast asset concentration", "Petrochemical feedstock exposure", "Carbon-intensive manufacturing"],
  },
  {
    id: "pkg",
    ticker: "PKG",
    companyName: "Packaging Corp",
    positionType: "LONG",
    markerSize: "small",
    coordinates: [41.8781, -87.6298],
    sector: "Packaging",
    positionMarketValue: 18.6,
    portfolioWeight: 15.1,
    annualRevenue: 8400,
    ebitdaMargin: 0.21,
    debt: 2600,
    interestExpense: 120,
    sharesOrExposureUnits: 82000,
    baselineValuationMultiple: 8.1,
    dailyRevenue: 23.0,
    repairCostSensitivity: 0.94,
    recoverySpeed: 0.81,
    hedgeRelevanceScore: 0.16,
    geographicExposure: { hurricane: 0.12, wildfire: 0.11, flood: 0.09, drought: 0.17, carbon: 0.28 },
    facilitiesInImpactZonePct: { hurricane: 0.03, wildfire: 0.08, flood: 0.04, drought: 0.07, carbon: 0.18 },
    climateSensitivity: { physicalDamage: 0.82, revenue: 0.78, cost: 0.96, credit: 0.88, valuation: 0.93 },
    thematicDrivers: ["Midwest logistics dependency", "Input-cost pass-through risk", "Industrial demand sensitivity"],
  },
];
