import type { PortfolioHolding, ScenarioEvent, SeverityLevel, TimeHorizon } from "./types";

export const TOTAL_PORTFOLIO_MARKET_VALUE = 35.0;
export const MAP_CENTER: [number, number] = [34.5, -92.0];
export const INITIAL_ZOOM = 5;
export const MARKER_PIXELS = { large: 54, medium: 46, small: 38 } as const;

export const SCENARIO_EVENTS: ScenarioEvent[] = [
  {
    id: "hurricane",
    icon: "\u{1F300}",
    label: "Gulf Coast Hurricane",
    summaryLabel: "Gulf Coast",
    epicenter: [28.5, -90.0],
    footprintType: "radius",
    primaryDrivers: ["Gulf Coast refinery concentration", "Coastal infrastructure exposure"],
  },
  {
    id: "wildfire",
    icon: "\u{1F525}",
    label: "California / Western Wildfire",
    summaryLabel: "Western U.S.",
    epicenter: [37.5, -120.0],
    footprintType: "radius",
    primaryDrivers: ["Insurance claims surge", "Property portfolio exposure"],
  },
  {
    id: "flood",
    icon: "\u{1F30A}",
    label: "Mississippi River Flood",
    summaryLabel: "Mississippi Basin",
    epicenter: [32.0, -90.5],
    footprintType: "radius",
    primaryDrivers: ["Southeast industrial property damage", "Gulf processing corridor disruption"],
  },
  {
    id: "drought",
    icon: "\u2600\uFE0F",
    label: "Texas Drought & Grid Stress",
    summaryLabel: "Texas",
    epicenter: [31.5, -98.0],
    footprintType: "radius",
    primaryDrivers: ["Power generation stress", "Refinery cooling constraints"],
  },
  {
    id: "carbon",
    icon: "\u26A1",
    label: "Carbon Tax Shock ($100/ton)",
    summaryLabel: "Systemic Transition Shock",
    footprintType: "systemic",
    primaryDrivers: ["Fossil fuel stranded asset repricing", "Insurance liability revaluation"],
  },
];

export const SEVERITY_LABELS: Record<SeverityLevel, string> = {
  1: "Cat 1",
  2: "Cat 2",
  3: "Cat 3",
  4: "Cat 4",
  5: "Cat 5",
};

export const TIME_HORIZON_LABELS: Record<TimeHorizon, string> = {
  "1w": "1 Week",
  "1m": "1 Month",
  "1q": "1 Quarter",
  "1y": "1 Year",
};

export const SEVERITY_RADII: Record<SeverityLevel, number> = {
  1: 150_000,
  2: 250_000,
  3: 350_000,
  4: 500_000,
  5: 700_000,
};

export const MOCK_PORTFOLIO: PortfolioHolding[] = [
  {
    id: "vlo",
    ticker: "VLO",
    companyName: "Valero Energy",
    positionType: "LONG",
    markerSize: "large",
    coordinates: [29.4241, -98.4936],
    sector: "Oil & Gas Refining",
    positionMarketValue: 12.0,
    portfolioWeight: 34.3,
    annualRevenue: 139009,
    ebitdaMargin: 0.0905,
    debt: 8900,
    interestExpense: 720,
    sharesOrExposureUnits: 250000,
    baselineValuationMultiple: 5.5,
    dailyRevenue: 380.8,
    repairCostSensitivity: 1.45,
    recoverySpeed: 0.58,
    hedgeRelevanceScore: 0.92,
    geographicExposure: { hurricane: 0.90, wildfire: 0.08, flood: 0.72, drought: 0.28, carbon: 0.82 },
    facilitiesInImpactZonePct: { hurricane: 0.75, wildfire: 0.02, flood: 0.55, drought: 0.20, carbon: 0.80 },
    climateSensitivity: { physicalDamage: 1.45, revenue: 1.35, cost: 1.40, credit: 1.15, valuation: 1.08 },
    thematicDrivers: ["Gulf Coast refinery concentration", "Crude supply chain dependency", "Hydrocarbon transition exposure"],
  },
  {
    id: "nrg",
    ticker: "NRG",
    companyName: "NRG Energy",
    positionType: "LONG",
    markerSize: "medium",
    coordinates: [29.7604, -95.3698],
    sector: "Independent Power",
    positionMarketValue: 8.0,
    portfolioWeight: 22.9,
    annualRevenue: 28000,
    ebitdaMargin: 0.15,
    debt: 8500,
    interestExpense: 650,
    sharesOrExposureUnits: 444444,
    baselineValuationMultiple: 10.5,
    dailyRevenue: 76.7,
    repairCostSensitivity: 1.30,
    recoverySpeed: 0.65,
    hedgeRelevanceScore: 0.72,
    geographicExposure: { hurricane: 0.75, wildfire: 0.15, flood: 0.55, drought: 0.45, carbon: 0.55 },
    facilitiesInImpactZonePct: { hurricane: 0.65, wildfire: 0.05, flood: 0.40, drought: 0.35, carbon: 0.42 },
    climateSensitivity: { physicalDamage: 1.28, revenue: 1.20, cost: 1.25, credit: 1.10, valuation: 1.05 },
    thematicDrivers: ["Texas grid dependency", "Power generation fleet concentration", "ERCOT market volatility"],
  },
  {
    id: "egp",
    ticker: "EGP",
    companyName: "EastGroup Properties",
    positionType: "LONG",
    markerSize: "small",
    coordinates: [32.2988, -90.1848],
    sector: "Industrial REIT",
    positionMarketValue: 5.0,
    portfolioWeight: 14.3,
    annualRevenue: 600,
    ebitdaMargin: 0.70,
    debt: 2300,
    interestExpense: 95,
    sharesOrExposureUnits: 62500,
    baselineValuationMultiple: 22.0,
    dailyRevenue: 1.64,
    repairCostSensitivity: 1.10,
    recoverySpeed: 0.72,
    hedgeRelevanceScore: 0.35,
    geographicExposure: { hurricane: 0.58, wildfire: 0.35, flood: 0.62, drought: 0.20, carbon: 0.15 },
    facilitiesInImpactZonePct: { hurricane: 0.42, wildfire: 0.12, flood: 0.50, drought: 0.08, carbon: 0.10 },
    climateSensitivity: { physicalDamage: 1.12, revenue: 1.18, cost: 1.08, credit: 1.12, valuation: 1.18 },
    thematicDrivers: ["Southeast industrial property exposure", "Sunbelt flood corridor", "FEMA flood map repricing"],
  },
  {
    id: "all",
    ticker: "ALL",
    companyName: "Allstate Corp",
    positionType: "LONG",
    markerSize: "large",
    coordinates: [42.0884, -87.9806],
    sector: "P&C Insurance",
    positionMarketValue: 10.0,
    portfolioWeight: 28.6,
    annualRevenue: 57364,
    ebitdaMargin: 0.119,
    debt: 8200,
    interestExpense: 650,
    sharesOrExposureUnits: 208333,
    baselineValuationMultiple: 7.2,
    dailyRevenue: 157.2,
    repairCostSensitivity: 0.85,
    recoverySpeed: 0.80,
    hedgeRelevanceScore: 0.65,
    geographicExposure: { hurricane: 0.85, wildfire: 0.70, flood: 0.78, drought: 0.25, carbon: 0.42 },
    facilitiesInImpactZonePct: { hurricane: 0.12, wildfire: 0.12, flood: 0.12, drought: 0.04, carbon: 0.28 },
    climateSensitivity: { physicalDamage: 0.55, revenue: 1.55, cost: 1.45, credit: 1.35, valuation: 1.28 },
    thematicDrivers: ["Catastrophe claims exposure", "Reinsurance repricing risk", "Multi-peril policy book"],
  },
];
